### ISSUE TITLE
Missing folder GLSL in release

### ISSUE THREAD

**Issue by KevinJue** [Insiteo/ios-v3#1]
Hello,
I tried to add your product in mine including your 3D features by following step by step http://dev.insiteo.com/api/pages/ios_3_3_gettingstarted#installation-project-setup.

In this starter you speak about a GLSL folder but the fact is that your release doesn't include this folder so i can't use 3D's.

where can i find it ?

**Comment by bleguelvouit** [comment]
Hi Kevin,
You will find this folder in the libs/InsiteoAPI.zip archive.
Baptiste.

**Comment by KevinJue** [comment]
Hello, 

Thanks, i found it in github master tree, just to say it's not included in release 3.2.4 so i wonder if 3D feature is supported in 3.2 ?

**Comment by bleguelvouit** [comment]
Hi,
The 3D feature is only available since the 3.3.0_RC0 release.
Baptiste.
