### ISSUE TITLE
Transitioning to ARC ?

### ISSUE THREAD

**Issue by KevinJue** [Insiteo/ios-v3#3]
Hello, 

I was just wondering, why don't use ARC and use to retaining/releasing manually ?

ARC has no GC runtime cost. The compiler inserts retains and releases in all the places you should have anyway. But it's smarter than you and can optimize out the ones that aren't actually needed.  (just like it can unroll loops, eliminate temporary variables, inline functions, etc.).

Moreover many project (arround 90% i think) use ARC, people can have some conflict with this event if then can resolve it by using -fno-objc-arc, so did you decide to switch for it in a future release ?

**Comment by bleguelvouit** [comment]
Hi Kevin,
We haven't planned transitioning to ARC for now.

**Comment by bleguelvouit** [comment]
Since the 3.4.1 release, the InsiteoSDK is now fully ARC compatible.
